### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by DeastinY** [slhck/audio-normalize#9]
$ ffmpeg-normalize -h
Traceback (most recent call last):
  File "c:\python33\lib\runpy.py", line 160, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python33\lib\runpy.py", line 73, in _run_code
    exec(code, run_globals)
  File "c:\Python33\Scripts\ffmpeg-normalize.exe\__main__.py", line 5, in <module>
  File "c:\python33\lib\site-packages\ffmpeg_normalize\__main__.py", line 96, in <module>
    if 'avconv' in FFMPEG_CMD:
TypeError: argument of type 'NoneType' is not iterable

**Comment by slhck** [comment]
Should be fixed now. Make sure you have ffmpeg or avconv installed in your PATH.

**Comment by DeastinY** [comment]
works thanks !
